# Generated by Django 4.1.3 on 2022-12-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_emailcheck"),
    ]

    operations = [
        migrations.DeleteModel(name="Emailcheck",),
    ]
