import Layout from "@md/components/layout";
import Head from "next/head";
import Navigation from "@md/components/navigation";
import { ManagePatients, RegisterTrain } from "@md/interfaces/manage.interface";
import { DoctorInfo } from "@md/interfaces/user.interface";
import Profile from "@md/components/profile";
import { useEffect, useState } from "react";
import ManageItem from "@md/components/manageItem";
import axiosClient from "@md/utils/axiosInstance";

export async function getStaticProps() {
    const resManages = await fetch("http://localhost:3000" + "/api/get-manages");
    const manageData = await resManages.json();

    // const resPatientNum = await fetch("http://localhost:3000" + "/api/get-doctor-patient-num");
    // const patientNumData = await resPatientNum.json();

    const resRegisterTrain = await fetch("http://localhost:3000" + "/api/get-train-list");
    const registerTrainData = await resRegisterTrain.json();

    // const resDoctor = await fetch("http://localhost:3000" + "/api/get-doctor");
    // const doctorData = await resDoctor.json();

    return {props: {manageData, registerTrainData}};
}

// 의사가 진료하는 환자들을 확인할 수 있는 페이지
export default function Manage({manageData, doctorData, patientNumData, registerTrainData}: {
    manageData: ManagePatients[] | null,
    doctorData: DoctorInfo,
    patientNumData: DoctorInfo,
    registerTrainData: RegisterTrain[] | null,
}) {
    const [tabIdx, setTabIdx] = useState(0);

    const [loading, setLoading] = useState(false);
    const [info, setInfo] = useState<DoctorInfo>();
    const [resPatientNum, setResPatientNum] = useState<DoctorInfo>();
    const [resRegisterTrain, setResRegisterTrain] = useState<RegisterTrain[]>();

    useEffect(() => {
        axiosClient.get('/api/user').then(response => {
            setInfo({
                _id: response.data._id,
                id: response.data.id,
                name: response.data.name,
                hospitalname: response.data.hospitalname,
            });
            setLoading(!loading);
        })
    }, []);

    useEffect(() => {
        if (info) {
            axiosClient.post('/api/manage_list', {id: info?.id}).then(response => {
                setResPatientNum({
                    _id: response.data.data._id,
                    name: response.data.data.name,
                    patientNum: response.data.data.patientNum?.toString(),
                });
                console.log(response.data.data.patientNum?.toString());
            });
        }
    }, [loading]);

    useEffect(() => {
        axiosClient.get('/api/patient_list').then(response => {
        });

    }, []);

    return (
        <div>
            <Head>
                <title>모션 닥터 | 의사 환자 관리페이지</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Navigation></Navigation>

            {
                tabIdx === 0 ?
                    <Profile doctorData={info!} patientNumData={null} registerTrain={registerTrainData}/> :
                    <Profile doctorData={info!} patientNumData={resPatientNum!} registerTrain={null}/>
            }

            <Layout>

                <div
                    className="flex mb-8 gap-6 w-full pb-3 border-b-[1px] border-gray-300 justify-center drop-shadow-2xl">
                    <div className={`${tabIdx === 0 && "font-bold"} hover:font-bold`} onClick={() => setTabIdx(0)}>등록 재활
                        코스 목록
                    </div>
                    <div className={`${tabIdx === 1 && "font-bold"} hover:font-bold`} onClick={() => setTabIdx(1)}>진찰 환자
                        목록
                    </div>
                </div>

                {
                    tabIdx === 0 ? <ManageItem manageData={null} registerTrainData={registerTrainData}/> :
                        <ManageItem manageData={manageData} registerTrainData={null}/>
                }
            </Layout>
        </div>
    );
};