import Layout from "@md/components/layout";
import Head from "next/head";
import Navigation from "@md/components/navigation";
import Item, { UploadItem } from "@md/components/upload/item";
import { useEffect, useRef, useState } from "react";

export default function Upload () {
    const [item, setItem] = useState({} as UploadItem);
    const [items, setItems] = useState([]);
    const inputRef = useRef<HTMLInputElement | null>(null);
    const nextId = useRef(0);

    const handleSubmit = () => {
        const data : UploadItem = {
            id: nextId.current,
            name: item.name,
            filePath: inputRef.current?.value,
        };
        setItems(items.concat(data));
        nextId.current += 1;
        setItem({name: "", filePath: ""});
        inputRef.current.value = null;
    };

    const handleRemove = (id) => {
        setItems(items.filter(idx => idx.id !== id));
    }

    const handleInputChange = (e) => {
        if (e.target.name === "filePath") setItem({ ...item, [e.target.name]: inputRef.current?.value });
        else setItem({ ...item, [e.target.name]: e.target.value });
    };


    return(
        <div>
            <Head>
                <title>모션 닥터 | 자세 등록</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation></Navigation>
            <Layout>
                <div>자세 등록</div>
                <div>의사번호</div>

                <div>
                    <input  name={"name"}
                            value={item.name}
                            type={"text"}
                            onChange={handleInputChange}/>
                    <input  name={"filePath"}
                            type={"file"}
                            ref={inputRef}
                            onChange={handleInputChange}/>
                    <button onClick={handleSubmit}>등록하기</button>
                </div>

                <div>
                    {
                        items.map((idx) => {return <Item key={idx.id} itemData={idx} handleRemove={handleRemove}/>})
                    }
                </div>

                <button>제출하기</button>
            </Layout>
        </div>
    );
};