# Generated by Django 4.1.3 on 2022-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="userID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("id", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
            ],
            options={"db_table": "userinfo", "managed": False,},
        ),
    ]
