# Generated by Django 4.1.3 on 2022-12-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emailcheck",
            fields=[
                (
                    "email",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("code", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "emailcheck", "managed": False,},
        ),
    ]
