import Head from "next/head";
import Navigation from "@md/components/navigation";
import Layout from "@md/components/layout";
import React, { useCallback, useEffect, useState } from "react";
import { DoctorSign } from "@md/interfaces/user.interface";
import { debounce } from "@md/utils/debounce";
import axios from "@md/utils/axiosInstance";

export default function Admin() {
    const [doctorListData, setDoctorListData] = useState<DoctorSign[]>([]);

    useEffect(() => {
        axios.get("/api/user").then((response) => {
            setDoctorListData(response.data);
            console.log(doctorListData)
        });
    }, []);


    // api 호출 한번만 적용
    const request = debounce((value: object) => {
        axios.post("/api/isapprove", value).then();
    }, 3000);

    const handleApproval = useCallback((approval: object) => request(approval), []);


    return (
        <div>
            <Head>
                <title>모션 닥터 | 의사 환자 관리페이지</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation></Navigation>

            <Layout>
                <div className="font-bold text-lg mb-5">승인 요청 목록</div>
                <div className="flex items-center py-3.5 font-bold border-b-2 border-gray-50">
                    <div className="w-[10%] flex justify-center">번호</div>
                    <div className="w-[20%] flex justify-center">이름</div>
                    <div className="w-[10%] flex justify-center">아이디</div>
                    <div className="w-[15%] flex justify-center">이메일</div>
                    <div className="w-[15%] flex justify-center">의사면허번호</div>
                    <div className="w-[20%] flex justify-center">병원명</div>
                    <div className="w-[10%] flex justify-center">승인상태</div>
                </div>
                {
                    doctorListData && doctorListData?.map((data: DoctorSign, idx) => {
                        return (
                            <div key={idx}
                                 className="flex justify-between hover:bg-color-primary-100 border-b-2 border-gray-50 py-3.5">
                                <div className="w-[10%] flex justify-center">{idx + 1}</div>
                                <div className="w-[20%] flex justify-center">{data.name}</div>
                                <div className="w-[10%] flex justify-center">{data.id}</div>
                                <div className="w-[15%] flex justify-center">{data.email}</div>
                                <div className="w-[15%] flex justify-center">{data.doctornum}</div>
                                <div className="w-[20%] flex justify-center">{data.hospitalname}</div>
                                <div className="w-[10%] flex justify-center">
                                    <input type="checkbox" defaultChecked={data.state}
                                           onChange={(e) => {
                                               handleApproval({id: data.id, state: e.target.checked})
                                           }}/>
                                </div>

                            </div>
                        );
                    })
                }
            </Layout>
        </div>
    )
}