import Head from "next/head";
import Navigation from "@md/components/navigation";
import Layout from "@md/components/layout";

export default function Intro() {
    return (
        <>
            <Head>
                <title>모션 닥터 | 프로젝트 소개</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation></Navigation>

            <Layout>
                <div className={'flex flex-col gap-6'}>
                    <h1 className={'text-2xl font-bold'}>Motion Doctor 모션닥터</h1>
                    <h2 className={'text-xl font-semibold'}>2023년 충북대학교 소프트웨어학과 졸업작품</h2>
                    <div>
                        <h3 className={'text-lg font-semibold'}>프로젝트 개요</h3>
                        <p>모션인식을 통해 재활키료 환자들의 올바른 재활 자세를 알려주는 디지털 헬스 서비스</p>
                    </div>
                    <div>
                        <h3 className={'text-lg font-semibold'}>프로젝트 진행 배경</h3>
                        <p>고령화 사회가 지속되면서 재활 치료에 대한 수요가 날로 증가하고 있다.<br/>그런데 재활 전문의의 수는 환자수에 비해 부족한 상황이어서,
                            재활 전문의의 부담이 커지고 있는 상황이다. 이에 따라, 23년도부터는 재활환자 재택의료팀을 구성하여 18개의 의료기관이 재택 치료를
                            지원하는 사업을 진행하고 있다고 한다.</p>
                        <p>재택 치료 중 <span className="text-color-primary-500">환자의 자세를 평가하는 시스템</span>을 개발하여 의료팀의 부담을
                            최소화하고자 한다.<br/>재택에서도
                            환자들이 재활을 스스로 원할하게 진행할 수 있도록 하는
                            것을
                            목표로
                            한다.</p>
                    </div>
                    <div>
                        <h3 className={'text-lg font-semibold'}>참여 인원</h3>
                        <p>송수영: 스켈레톤을 활용한 모션인식 알고리즘 개발</p>
                        <p>오지우: 백엔드 시스템 개발</p>
                        <p>송수영: 프론트엔드 시스템 개발</p>
                    </div>
                </div>
            </Layout>
        </>
    );
}