import Navigation from "@md/components/navigation";
import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import WebCam from "@md/components/webcam";


export default function Test() {
    const data = [
        {
            tag: '어깨운동',
            img: '/videos/KakaoTalk_Video_2023-03-31-10-57-34.mp4',
        },
        {
            tag: '호흡',
            img: ''
        }
    ];

    const vidRef = useRef<any>(null);
    const [videoData, setVideoData] = useState(data[0]);
    const [isPause, setIsPause] = useState(false);

    const handlePlayVideo = () => {
        if (!isPause) {
            vidRef.current.play();
        } else {
            vidRef.current.pause();
        }
    }

    useEffect(() => {
        alert("**새로고침이 될 시, 기존 테스트 데이터들이 모두 삭제됩니다** \n 테스트 영상의 길이는 1분 이상이어야 합니다");
    }, [])

    return (
        <div className="h-screen overflow-hidden">
            <Head>
                <title>모션 닥터 | 자세 검사</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation></Navigation>

            <div className="flex h-full relative">
                <div className="h-full w-[20%] flex flex-col">
                    <div
                        className="flex h-full flex-col overflow-hidden drop-shadow-sm overflow-y-scroll divide-y divide-stone-200 divide-solid">
                        {
                            data.map(item => {
                                return <div key={item.tag} onClick={() => {
                                    setVideoData(item);
                                }}
                                            className={`${videoData.tag === item.tag && "bg-color-primary-100 font-bold"} py-5 px-3 text-center cursor-pointer `}>
                                    {item.tag}
                                </div>
                            })
                        }
                    </div>

                    <a className="fixed w-[20%] inset-x-0 bottom-0 py-5 px-3 text-center cursor-pointer"
                       href={`/patient/upload`}>자세등록하기</a>
                </div>
                <div className="h-full w-[40%] relative">
                    <div className='w-full h-full z-0'>
                        <WebCam tag={videoData.tag}></WebCam>
                    </div>
                </div>
                <div className="h-full w-[40%]">
                    {videoData.img &&
                        <video controls src={videoData.img}
                               style={{width: "100%", height: "93%", background: 'black', cursor: 'pointer'}}
                               onClick={() => {
                                   setIsPause(!isPause);
                                   handlePlayVideo();
                               }} ref={vidRef}
                        ></video>
                    }
                </div>
            </div>

        </div>
    );
}