import Link from "next/link";
import React, { useEffect, useState } from "react";
import { CourseInfo } from "@md/interfaces/course.interface";
import Layout from "@md/components/layout";
import Head from "next/head";
import Navigation from "@md/components/navigation";
import axios from "axios";
// 의사가 등록한 재활코스 모두 확인할 수 있는 페이지
export default function Test() {
    const [courseInfoList, setCourseInfoList] = useState<CourseInfo[]>();

    useEffect(() => {
        axios.get(process.env.NEXT_PUBLIC_API_KEY + "/api/video_list").then((res) => {
            setCourseInfoList(res.data.data);
        });
    }, [])

    return (
        <div>
            <Head>
                <title>모션 닥터 | 등록 재활 코스 확인 페이지</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation></Navigation>

            <Layout>
                <div>
                    <div className="mx-12 font-bold text-lg my-4">등록 재활 코스 목록</div>
                    <div className="flex flex-col mx-12 border-x border-t border-gray-50">
                        <div className="flex items-center py-3.5 font-bold border-b-2 border-gray-50">
                            <div className="w-[15%] flex justify-center">번호</div>
                            <div className="w-[20%] flex justify-center items-center">담당 의사 명</div>
                            <div className="w-[20%] flex justify-center">병원명</div>
                            <div className="w-[30%] flex justify-center">재활 코스 명</div>
                            <div className="w-[15%] flex justify-center">등록 운동 개수</div>

                        </div>
                        {
                            courseInfoList && courseInfoList!.map((data: CourseInfo, idx) => {
                                return (
                                    <Link key={idx} href={'/test/' + data.type + '-' + data.typeIdx}
                                          className="flex justify-between hover:bg-color-primary-100 border-b-2 border-gray-50 py-3.5">
                                        <div className="w-[15%] flex justify-center">{idx + 1}</div>
                                        <div className="w-[20%] flex justify-center">{data.doctor_name}</div>
                                        <div className="w-[20%] flex justify-center">{data.doctor_hospitalName}</div>
                                        <div className="w-[30%] flex justify-center">{data.type}</div>
                                        <div className="w-[15%] flex justify-center">{data.video_num}</div>
                                    </Link>
                                );
                            })
                        }
                    </div>
                </div>
            </Layout>
        </div>
    );
}