import Head from "next/head";
import Navigation from "@md/components/navigation";
import React from "react";
import Layout from "@md/components/layout";
import axios from "axios";
import { PostureInfo } from "@md/interfaces/posture.interface";

export async function getStaticProps() {
    const resPostures = await axios("http://localhost:3000" + "/api/get-patient-postures");
    const posturesData = resPostures.data;
    return {props: {posturesData}};
}

export default function Postures({posturesData}: { posturesData: PostureInfo[] }) {
    return (
        <div>
            <Head>
                <title>모션 닥터 | 환자 자세 목록 페이지</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation></Navigation>

            <Layout>
                <div className="mx-12 font-bold text-lg my-4">환자 진료 내역</div>
                <div className="flex flex-col mx-12 border-x border-t border-gray-50">
                    <div className="flex items-center py-3.5 font-bold border-b-2 border-gray-50">
                        <div className="w-[10%] flex justify-center">번호</div>
                        <div
                            className="w-[25%] flex justify-center">재활 코스 명
                        </div>
                        <div className="w-[15%] flex justify-center">재활 코스내 운동 개수</div>
                        <div className="w-[15%] flex justify-center">담당의사</div>
                        <div className="w-[20%] flex justify-center">병원명</div>
                        <div className="w-[15%] flex justify-center">피드백 결과</div>
                    </div>
                    {
                        posturesData && posturesData!.map((data: PostureInfo, idx) => {
                            return (
                                <div key={idx}
                                     className="flex justify-between hover:bg-color-primary-100 border-b-2 border-gray-50 py-3.5">
                                    <div className="w-[10%] flex justify-center">{idx + 1}</div>
                                    <div className="w-[25%] flex justify-center">{data.trainTitle}</div>
                                    <div className="w-[15%] flex justify-center">{data.trainNum}</div>
                                    <div className="w-[15%] flex justify-center">{data.doctorName}</div>
                                    <div className="w-[20%] flex justify-center">{data.hospitalName}</div>
                                    <div className="w-[15%] flex justify-center">{data.counselResult}</div>
                                </div>
                            );
                        })
                    }
                </div>
            </Layout>
        </div>
    )
}