import Head from "next/head";
import Navigation from "@md/components/navigation";
import React, { useEffect, useState } from "react";
import Layout from "@md/components/layout";
import { PostureInfo } from "@md/interfaces/posture.interface";
import axiosClient from "@md/utils/axiosInstance";
import Link from 'next/link'
import { UserInfo } from "@md/interfaces/user.interface";

export default function Postures() {
    const [resPostures, setResPostures] = useState<PostureInfo[]>();
    const [isDeleted, setIsDeleted] = useState<boolean>(false);
    const [userInfo, setUserInfo] = useState<UserInfo>();

    useEffect(() => {
        axiosClient.get('/api/user').then(response => {
            setUserInfo(response.data);
        })
    }, []);


    useEffect(() => {
        axiosClient.get('/api/test_list').then(response => {
            setResPostures(response.data.data);
        });
    }, [isDeleted]);

    return (
        <div>
            <Head>
                <title>모션 닥터 | 환자 자세 목록 페이지</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navigation></Navigation>

            <Layout>
                <div className="mx-12 font-bold text-lg my-4"><span
                    className={'text-color-primary-500'}>{userInfo?.name}</span> 환자의 수강 내역
                </div>
                <div className="flex flex-col mx-12 border-x border-t border-gray-50">
                    <div className="flex items-center py-3.5 font-bold border-b-2 border-gray-50">
                        <div className="w-[5%] flex justify-center">번호</div>
                        <div
                            className="w-[20%] flex justify-center">재활 코스 명
                        </div>
                        <div className="w-[10%] flex justify-center">운동 개수</div>
                        <div className="w-[15%] flex justify-center">담당의사</div>
                        <div className="w-[15%] flex justify-center">병원명</div>
                        <div className="w-[10%] flex justify-center">AI 피드백</div>
                        <div className="w-[20%] flex justify-center">의사 피드백</div>
                        <div className="w-[5%] flex justify-center">삭제</div>
                    </div>
                    {

                        resPostures && resPostures!.map((data: PostureInfo, idx) => {
                            return (
                                <Link href={{
                                    pathname: `/result/${userInfo?.uid}`,
                                    query: {"type": `${data.trainTitle}-${data.idx}`}
                                }}
                                      key={idx}
                                      className="flex justify-between hover:bg-color-primary-100 border-b-2 border-gray-50 py-3.5">
                                    <div className="w-[5%] flex justify-center">{idx + 1}</div>
                                    <div className="w-[20%] flex justify-center">{data.trainTitle}</div>
                                    <div className="w-[10%] flex justify-center">{data.trainNum}</div>
                                    <div className="w-[15%] flex justify-center">{data.doctorName}</div>
                                    <div className="w-[15%] flex justify-center">{data.hospitalName}</div>
                                    <div className="w-[10%] flex justify-center">{data.score}</div>
                                    <div
                                        className="w-[20%] flex justify-center">{data.counselResult ? data.counselResult.toString() : "0"}</div>
                                    <div className="w-[5%] flex justify-center">
                                        <button onClick={(e) => {
                                            e.preventDefault();
                                            axiosClient.post('/api/remove_video', {type: `${data.trainTitle}-${data.idx}`}).then((res) => {
                                                setIsDeleted(!isDeleted);
                                            });
                                        }}>
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                 strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                                                <path strokeLinecap="round" strokeLinejoin="round"
                                                      d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"/>
                                            </svg>
                                        </button>
                                    </div>
                                </Link>
                            );
                        })
                    }
                </div>
            </Layout>
        </div>
    )
}